### ISSUE TITLE
Install non-english manpages

### ISSUE THREAD

**Issue by suve** [andy5995/rmw#106]
Non-english manpages should be installed in 
```
$MANDIR/$LANGUAGE_CODE/man1/
```
Assuming `/usr/share/man` for the page catalog, the Polish manpage should be installed as
```
/usr/share/man/pl/man1/rmw.1
```

**Comment by andy5995** [comment]
Thank you @suve 

I forgot to label this ticket.

If no one takes this ticket,  I'll try to get to this within the next couple weeks. Perhaps it would be time for a release once it's done.

**Comment by andy5995** [comment]
The diff from the commit directly above shows a lot of changes, but some were automatically generated when I ran autoconf and automake.

The main changes I did were:

https://github.com/andy5995/rmw/commit/ef5dd882b1e124954dccbac66852f9b5fa4031dc#diff-559b8943197758815ea3c54626c404db

https://github.com/andy5995/rmw/commit/ef5dd882b1e124954dccbac66852f9b5fa4031dc#diff-c949f93d03f44a4217d7a138f9e2e54a

https://github.com/andy5995/rmw/commit/ef5dd882b1e124954dccbac66852f9b5fa4031dc#diff-67e997bcfdac55191033d57a16d1408a
