### ISSUE TITLE
Translate English man page to NL (Nederlands)

### ISSUE THREAD

**Issue by andy5995** [andy5995/rmw#109]
@sexybiggetje, Would you be interested in translating the [man page](https://github.com/andy5995/rmw/blob/master/man/rmw.1) to NL?

Extra details are here:

https://github.com/andy5995/rmw/issues/77#issuecomment-344679744

Please don't hesitate to tell me if you find any text that I should change to make things more easily translatable.

**Comment by sexybiggetje** [comment]
Sure, no problem
