### ISSUE TITLE
missing man page

### ISSUE THREAD

**Issue by andy5995** [andy5995/rmw#11]
I've decided that a man page would be helpful.

**Comment by suve** [comment]
Hi. Is the Readme up to date? I could create a manpage by borrowing most of the text from the Readme.

**Comment by andy5995** [comment]
Hi @suve Thanks for the offer!

Yes, the README is up to date.

Please be sure to create the patch on a separate branch of your fork. The procedure is outlined here:
https://github.com/andy5995/rmw/wiki/Contributing

Feel free to let me know if you have any questions. I'm on periodically throughout the day.
