### ISSUE TITLE
Create Finnish translation

### ISSUE THREAD

**Issue by andy5995** [andy5995/rmw#118]
@sapake , would you be interested in doing this?

Instructions for creating translations are at https://github.com/andy5995/rmw/wiki/Translating

This is the .pot file that needs translating:
https://github.com/andy5995/rmw/blob/master/po/rmw.pot

Translators are encouraged to join the [chat room](https://join.slack.com/t/removetowaste/shared_invite/enQtMjU3NTA0NTI2OTgzLTkzMzQxNDhjYzlkM2UxMTA2MzJjNWYyZjAyYzkyNWNmZjJmYWZmYjUyODk2NzNkNzBhMzFjOGZkMTg2MzAxMTM)

**Comment by sapake** [comment]
Yes, I could look into it this weekend maybe.

**Comment by andy5995** [comment]
sapake said he'll have time this weekend to look things over.
