### ISSUE TITLE
Segfault on first run

### ISSUE THREAD

**Issue by cryptarch** [andy5995/rmw#128]
Hi, I found this project through 24 Pull Requests. It looks interesting but my experience has not been promising so far 😄 

When I try running rmw for the first time it segfaults straight away. It might be because I am not installing it as a system package, instead it is going into my home directory. I've tried both the following methods:

~~~{.sh}
./configure --prefix=$HOME
./make
./make install
mkdir -p ~/.config/rmw
cp ~/etc/rmwrc ~/.config/rmw/
~~~

~~~{.sh}
./configure --prefix=/
./make
mkdir build
DESTDIR=$PWD/build make install
ln -sv $PWD/build/bin/rmw ~/bin/rmw
ln -sv $PWD/build/man/man1/rmw.1.gz ~/man/man1/
mkdir -p ~/.config/rmw/
cp ./build/etc/rmwrc ~/.config/rmw/
~~~

I'm conscious that I'm not following the given instructions exactly, but after a lot of experience with Linux software, it seems like what I am doing _should_ work.

I'm going to dig around a bit to see if I can figure what is causing the segfault, but in the meantime I thought you would want this on your radar.

**Comment by andy5995** [comment]
>it seems like what I am doing should work.

It either should work, or produce an error other than a segfault.

You've caught a bug! The system-wide config file is etc/rmwrc and the user one is  ~/.config/rmw/config

As I replicated your steps, I see that if ~/.config/rmw/rmwrc is used as the config file, a segfault is produced.

Thanks for the bug report! I'll check it out right now
