### ISSUE TITLE
adding more error checking

### ISSUE THREAD

**Issue by andy5995** [andy5995/rmw#13]
More error checking needs to be added upon opening and closing files.

**Comment by andy5995** [comment]
This is how I've started it. I haven't committed any changes yet though. There'll likely be some evolution as to the exact technique and how the errors are displayed to the user.
```
FILE *cfgPtr;

  /**
   * if config_file isn't found in home directory,
   * else open the system default (SYSCONFDIR/rmwrc)
   */
  if (!file_not_found (config_file))
  {
    cfgPtr = fopen (config_file, "r");

    /**
     * It exists. Any problem opening it for reading?
     */
    if (cfgPtr == NULL)
    {
      perror ("get_config_data");
      fprintf (stderr, "Error %d reading %s\n", errno, config_file);
    }
  }
```
      Upon successful completion fopen(), fdopen() and freopen() return a
       FILE pointer.  Otherwise, NULL is returned and errno is set to
       indicate the error.
[fopen() man page](http://man7.org/linux/man-pages/man3/fopen.3.html)

And for closing:
```
if (fclose (undo_file_ptr) == EOF)
      {
        perror ("main()");
        fprintf (stderr, "Error %d while closing %s\n", errno, undo_path);
      }
```
    Upon successful completion 0 is returned.  Otherwise, EOF is returned
    and errno is set to indicate the error
[fclose() man page](http://man7.org/linux/man-pages/man3/fclose.3.html)

**Comment by StanleySweet** [comment]
Looks a bit overkill for doxygen comments :)

**Comment by andy5995** [comment]
Hi Stan.

I'm not exactly clear on what you mean. Could you explain a little further?

**Comment by andy5995** [comment]
I think there's checking on all instances of files getting opened or closed. If I've missed any, feel free to make a PR.

**Comment by andy5995** [comment]
A lot of error-checking has been put in place since this ticket was first created. I need to review the code and potentially write a ticket with a narrower scope
