### ISSUE TITLE
Improve handling of plural forms

### ISSUE THREAD

**Issue by suve** [andy5995/rmw#133]
Some messages in the program use two different strings: a "1 item" one, and a "more than 1 item" one, for example:
```
1 file removed
%d files removed
```
While this satisfies the rules of English grammar, it is not enough for many other languages, which have more complicated rules - for example, in Polish, this would be:
```
usunięto 1 plik
usunięto 2-4 pliki
usunięto 5-21 plików
usunięto 22-24 pliki
usunięto 25-31 plików
[...]
```
As can be seen, there are three different forms in use.

Universal support for any language can be achieved using the _plural forms_ feature of gettext.
https://www.gnu.org/software/gettext/manual/html_node/Plural-forms.html

**Comment by andy5995** [comment]
Thanks for bringing this to my attention. Is anyone interested in working on this?

**Comment by andy5995** [comment]
I'll take this ticket.
