### ISSUE TITLE
Status shown when purge is running should change conditionally

### ISSUE THREAD

**Issue by andy5995** [andy5995/rmw#137]
This was the output when I ran

    RMWTRASH=empty rmw -fg

```
Purging files (purge_after = 45) ...
160 files purged
```

In that case, showing **purge_after = 45** is not relevant, so should be changed to indicate that an "empty" is being performed.

**Comment by GoldmanCPSciences** [comment]
hey, I'm a recent graduate with a Bachelors in Computer Science. C is not my most used language but I'm interested to learn more about it for a future job I might be getting. Do you think I could take a stab at this? What exactly do you want in the %u area? just a "now performing purge on etc."?

**Comment by andy5995** [comment]
@GoldmanCPSciences sure, you could take a stab at this! Thanks for the offer

The regular purge removes files after x number of days, as shown in the first post.

When rmw is used like this..

`RMWTRASH=empty rmw -ffg`

It will completely erase all the files in the WASTE folders, regardless of the purge_after variable.

So if the command above is used, purge_after is irrelevant. The text should read something like.. "Emptying waste folders..." , and this:

`(purge_after = 45)`

should not appear at all.

If you make some changes to the code, you can test it by running test/purge.sh

Although the output generated by the script is not very clean, you can see in the script where RMWTRASH=empty is used and shouldn't have any problem seeing the results of any code changes you make.

**Comment by GoldmanCPSciences** [comment]
can't you just... delete that portion of the code if its not supposed to be there and then change the "purging files.... " part to "emptying waste folders...."? does it just not remove everything that its supposed to? I'm a little confused ^^;

**Comment by andy5995** [comment]
The normal purge feature is to remove files after x number of days (specified in the config file). So when the user sees `(purge_after = 45)`, it's just a reminder as to what that value is set at. Though the message "purging files (purge_after = 45)" isn't very accurate either - you bring up a good point. Perhaps it should be something like "purging files rmw'ed more than 45 days ago"..

If the rmw command is preceded with `RMWTRASH=empty `, then purge will empty the WASTE folders, with no regard for when it was rmw'ed. A complete empty, so displaying the x value isn't relevant.

So there are 2 different behaviors for purge, and therefore 2 different output messages.

Does that help clarify things?

**Comment by GoldmanCPSciences** [comment]
Got it. Thanks, I'll start working on it soon if you're ok with that. ^_^

**Comment by andy5995** [comment]
Yes, you have a green light. :)

**Comment by andy5995** [comment]
I know I have to decide the exact text to use.

`Purging files (purge_after = %u)` can be replaced with
`purging files based on number of days in the waste folders (%u)...`

And when RMWTRASH=empty is used:

`RMWTRASH=empty: purging all files in the waste folders...`

If you have different suggestions, run them by me, @GoldmanCPSciences

**Comment by GoldmanCPSciences** [comment]
I like both of those.

**Comment by sexybiggetje** [comment]
How about:

Situation 1; regular purge after x amount of days:
"Purging files older than the configured %u days..."

Situation 2; empty the waste folder with RMWTRASH=empty
"Purging all files ignoring the configured %u days..."

And maybe Situation 2 should be preceded with a "Are you completely sure?" [y/n] option? Ofcourse when -f is passed it would suppress this extra safety measure.

_Also; three database admins walked into a NoSQL bar. A little later, they walked out because they couldn’t find a table._

**Comment by GoldmanCPSciences** [comment]
sounds good. I'll try to get started tomorrow. ^_^

**Comment by andy5995** [comment]
@sexybiggetje wrote:
>"Purging files older than the configured %u days..."

This would be the simplest.. or something like "Purging files based on age..."

But neither is accurate. It's not about the age of the files, but when they were "rmw'ed".

My suggestion above:
>purging files based on number of days in the waste folders (%u)...

is longer than I'd like it to be, but it accurately states what's happening.

@sexybiggetje wrote:
>And maybe Situation 2 should be preceded with a "Are you completely sure?" [y/n] option? Of course when -f is passed it would suppress this extra safety measure.

The -fg is actually required for RMWTRASH=empty to operate. I decided to code it that way intentionally.. for the extra confirmation, iirc. :)

The idea of extra confirmation was discussed when the feature was implemented.

Not only is the `-f` required, but the fact that the user must precede the rmw command with RMWTRASH=empty should be hopefully enough confirmation, imo. (It's a lot more confirmation than users get with `rm -rf` ;) )

Thank you for the perspective @sexybiggetje :) Now that I've explained my thinking, do you agree with it, or would  you do anything differently?

**Comment by sexybiggetje** [comment]
How about for situation 1:
"Purging files longer in your waste folder than the configured %u days..." ?

I understand your thinking, and affirm the flags itself being enough. Consider my suggestion void on that matter.

**Comment by GoldmanCPSciences** [comment]
well that explains why I wasn't able to get my secondary solution to work XD

this is what I came up with. 
<img width="705" alt="screen shot 2018-01-14 at 5 27 26 pm" src="https://user-images.githubusercontent.com/17244848/34964139-55f84336-fa09-11e7-9c7f-32f3fd2a48de.png">
should I just change the line and delete everything else?

**Comment by andy5995** [comment]
Sometimes, to send snippets of code, you'd want to use https://gist.github.com/

In this case, you can just submit a pull request; then I can view the [diff output](https://unix.stackexchange.com/questions/81998/understanding-of-diff-output) and also use it to apply a temporary patch for testing.

Doesn't matter if you're done with the patch; it's easy enough to update a pull request

**Comment by GoldmanCPSciences** [comment]
Sorry ^^; I'll get the pull request.

**Comment by andy5995** [comment]
No worries, mate. All part of the learning process.

Oh, and here are the PR instructions. I think maybe I need to make it more visible, with a link in the README probably.
