### ISSUE TITLE
code tightening and cleanup

### ISSUE THREAD

**Issue by andy5995** [andy5995/rmw#18]
This is related to #10

I let rmw since for a few years before I started working on it again. I've been re-writing a lot of the code, but there's still a lot more that can be done, and I'm still learning.

If anyone sees any chunks of code that he or she would like to fix, feel free. Whether it be 2 lines, or 50, it would be appreciated. Or if you just have suggestions, I'm all ears.

See this page on [contributing](https://github.com/andy5995/rmw/wiki/Contributing) if you have any questions. Thanks!

**Comment by parthsuresh** [comment]
Hi Andy, I'd like to be a part of this project if it's OK. I have some experience with C, but I'm new to the Linux environment. Please tell me what to do!

**Comment by andy5995** [comment]
@parthsuresh Most of this project uses ANSI C, code that is "native" to Windows or Linux. Having little or no Linux experience shouldn't be a problem.

Do you use IRC? We can work out some details in #rmw on QuakeNet. Otherwise the forum on SF https://sourceforge.net/p/rmw/discussion/ would be the next best option.

One of the first things you'll want to do is "fork" this repo (upper right corner of project page). Do you have any experience with git yet?

**Comment by parthsuresh** [comment]
@andy5995 Thanks for responding! I'll be reaching out to you through your IRC channel. Hope to talk to you soon!

**Comment by andy5995** [comment]
Also, @parthsuresh, have a look at this and it should answer some of your questions:
https://github.com/andy5995/rmw/wiki/Contributing

**Comment by andy5995** [comment]
This doesn't have to be done all at once. Anyone that notices a few lines of code that could be tightened can [submit a PR](https://github.com/andy5995/rmw/wiki/Contributing).

**Comment by andy5995** [comment]
I need to review the code and potentially write a ticket with a narrower scope.
