### ISSUE TITLE
no info file found when restoring symlinks

### ISSUE THREAD

**Issue by andy5995** [andy5995/rmw#27]
rmw is not finding a trashinfo file for symlinks after they are rmw'ed

**Comment by andy5995** [comment]
@parthsuresh

The function used to see if a file is a regular file, a symlink, or a directory is `file_not_found()` in primary_funcs.c

I haven't looked to see what's causing this problem yet.

If you're interested in trying to fix this, here are the steps.

1. reproduce the issue by creating a symlink, rmw'ing it, then `rmw -u`
2. you'll see a message that no info file was found

Possible causes:
1. a missing step in the mkinfo() function
2. a missing step in the Restore() function

**Comment by parthsuresh** [comment]
@andy5995 I'll try to resolve this issue.

**Comment by andy5995** [comment]
Ok. Thanks Remember to switch back to the develop branch before creating the issue_27 branch.

And when you're on develop, it wouldn't be a bad idea to fetch upstream and merge upstream/develop again. If you go to long without syncing, you or I may end up with merge conflicts.

**Comment by andy5995** [comment]
I found the problem, but haven't figured out a fix for it yet.

The info file is getting created properly.

When the symlink is being prepared for ReMoval, realpath() isn't used
[main.c L286](https://github.com/andy5995/rmw/blob/8dfae4fd4468049023a84de4ed92e676fbdf33a1/src/main.c#L286)

During restore, however, a realpath is needed to get the full path for restoration, so it can match it up with the right info file in the right WASTE dir.

[restore_rmw.c L60](https://github.com/andy5995/rmw/blob/f7a3ab115fee1f9dedb4398794c6060c1bd8a904/src/functions/restore_rmw.c#L60) The realpath resolves to the path or file the symlink actually points to.

**Comment by andy5995** [comment]
I asked the question on StackOverflow: How to [determine which directory a file is in](http://stackoverflow.com/questions/39524417/c-program-determine-which-directory-a-file-is-in)

**Comment by parthsuresh** [comment]
lstat source code 
/* lstat works differently on Linux and Solaris systems.  POSIX (see
   `pathname resolution' in the glossary) requires that programs like `ls'
   take into consideration the fact that FILE has a trailing slash when
   FILE is a symbolic link.  On Linux systems, the lstat function already
   has the desired semantics (in treating `lstat("symlink/",sbuf)' just like
   `lstat("symlink/.",sbuf)', but on Solaris it does not.

   If FILE has a trailing slash and specifies a symbolic link,
   then append a `.' to FILE and call lstat a second time. 

So is removing the trailing slash okay?

**Comment by andy5995** [comment]
> So is removing the trailing slash okay?

As far as I know so far. :)

**Comment by andy5995** [comment]
Fixed, closed.
