### ISSUE TITLE
disable verbose mode by default

### ISSUE THREAD

**Issue by andy5995** [andy5995/rmw#30]
Presently, there is an option for verbose, but rmw is pretty verbose when rmw'ing file, purging, etc.

Now that I've put a lot more error-checking in place, I'm more confident that I can let rmw behave more like the 'mv' or 'rm' command.

When a file is 'rmw'ed, the output is like this:
'temp' -> '/home/andy/temp/.local/share/Trash.test/files/temp_001920-160910'

(See Line 299 main.c)

That needs to be changed so it only appears if "verbose" is set to 1.

verbose is already declared in rmw.h, it's a global, and assigned 1 if -v or --verbose is added as an argument.

A similar change needs to be made to the purge() function. When a file is purged, the output shows a '-' sign next to the file.

(See Line 441 purging_rmw.c)

**Comment by parthsuresh** [comment]
@andy5995 here's the patch for this issue:

http://pastebin.com/FMsGtLxS

**Comment by andy5995** [comment]
Thanks. It looks like that code will work, but to be consistent, here's how the formatting should be:

1. Braces unneeded
2. The == 1 isn't needed. If verbose == 1 then verbose is true, so if (verbose) is all that's needed there
3. Indentation of 2 spaces after the if statement

Did you build and test it?

**Comment by andy5995** [comment]
Come to think of it, I'd like to see a counter added also. It will display the total number of files rmw'ed regardless of what verbose is set to. The output will show when rmw is finished.

There is already a counter for purge. You can look at that to get the general idea of how the string will get displayed to users.

The variable name and type? int rmwed_files.

The string?
"x files have been ReMoved to Waste"

**Comment by andy5995** [comment]
Well done! :)
