### ISSUE TITLE
Documentation review prior to release of v2016.09.xx

### ISSUE THREAD

**Issue by andy5995** [andy5995/rmw#47]
@parthsuresh, and anyone else, I updated the docs and pushed everything to the [next release branch](https://github.com/andy5995/rmw/tree/next_release).

I'd like to ask if they could be proofread before the release.

1. Is the wording clear?
2. Could the instructions or explanations be more concise?
3. Typos or grammatical errors
4. Anything noteworthy that I omitted?

I think the most efficient method of sending your suggested edits is through a PR, or by using http://pastebin.com

These are the primary files that need proof-reading:

[README](https://github.com/andy5995/rmw/blob/next_release/README)
[NEWS](https://github.com/andy5995/rmw/blob/next_release/NEWS)
[etc/rmwrc](https://github.com/andy5995/rmw/blob/next_release/etc/rmwrc)
[rmwrc_config.example](https://github.com/andy5995/rmw/blob/next_release/rmwrc_config.example)

If you have any questions, post them here or create a new topic on the [rmw forum](https://sourceforge.net/p/rmw/discussion/)

I plan to release Monday or Tuesday. If anyone needs more time to proof the docs, please let me know.

**Comment by ajphukan** [comment]
.md missing in each files  end

**Comment by andy5995** [comment]
Thanks for noting that @ajphukan . I generally avoid .md files. Because they're used to display files with _markdown_ , I often find I have to redo something that's already done in plain text. Also, if I use a README.md that contains markdown syntax, then a person opening it with a text editor, or viewing it with `less`, etc. would be seeing all the markdown syntax.

I'm not opposed to markdown though - I use it for the issues here, and the wiki.

**Comment by ajphukan** [comment]
Thanks @andy5995  for explaning the detail ... :)
