### ISSUE TITLE
use return value of getenv()

### ISSUE THREAD

**Issue by andy5995** [andy5995/rmw#49]
@parthsuresh we should be checking the return value of [getenv()](http://www.tutorialspoint.com/c_standard_library/c_function_getenv.htm). If it returns NULL, it kind of has an impact on the rest of the program ;)

If it's NULL, we should show an error msg
"Error: Environmental variable $HOME can't be used. Unable to determine home directory"

exit the program by returning 1;

**Comment by ajphukan** [comment]
There is multiple use of getenv() in [lines](https://github.com/andy5995/rmw/blob/1e92f1f5dc616e555991bf84933306f7ee07e20a/src/main.c#L131-L133)

I like to work on the above issue and the bug fix.

**Comment by ajphukan** [comment]
I like to work on it ..
And there is a multiple use of getenv() at  [lines](https://github.com/andy5995/rmw/blob/e735bbce9a35b0c9ae5d31aed61ed77379f1b658/src/main.c#L131-L133)  
We can replace it with single call and save that data to avariable ..

**Comment by andy5995** [comment]
Sure, go ahead, I'll take a look. Thanks, @ajphukan
