### ISSUE TITLE
Warnings when building

### ISSUE THREAD

**Issue by andy5995** [andy5995/rmw#55]
Anyone want to fix the warnings that show up when building?

https://travis-ci.org/andy5995/rmw/builds/162108775

The warning regarding realpath() is caused by the problem mentioned here:
http://stackoverflow.com/questions/33550771/my-realpath-return-null-for-files?rq=1

Once we get realpath() to not always return NULL, we can get rid of the [resolve_path() function:](https://github.com/andy5995/rmw/blob/1e92f1f5dc616e555991bf84933306f7ee07e20a/src/functions/strings_rmw.c#L168)

**Comment by andy5995** [comment]
fgets() warning is fixed.

**Comment by ajphukan** [comment]
[linke that i get  in source code](http://cboard.cprogramming.com/c-programming/171131-realpath-resolves-path-but-errno-set-2-a.html)

After checking the function i got conclusion 
rexolvepath generaly create the path first then it checks therefore you are getting the path as well the error 2

[line no 176](https://github.com/andy5995/rmw/blob/1e92f1f5dc616e555991bf84933306f7ee07e20a/src/functions/strings_rmw.c#L176)


```c
dest[0] = '\0';
/* 
realpath (str, dest);

  if (strlen (dest) != 0)
    return 0;

  fprintf (stderr, "Error: realpath() failed on string %s\n", str);
return 1;
*/
if(realpath(str,dest)!=NULL)
 return 0;
else
{
 fprintf (stderr, "Error: realpath() failed on string %s\n", str);
return 1;
}

```

**Comment by andy5995** [comment]
Closed. See #63 for more comments on the realpath issue.

**Comment by andy5995** [comment]
I had to do some more work on resolve_path()
https://github.com/andy5995/rmw/commit/1987cef05db5aef132efe9037123b0dc66d1d903

I'm using realpath() again. The "always NULL" problem is fixed.

Trying to use PWD had some unacceptable side effects, but I was able to ditch PWD in this last rewrite.
