### ISSUE TITLE
undo file should be removed once -u successfully restores the files

### ISSUE THREAD

**Issue by andy5995** [andy5995/rmw#58]
After rmw -u is run, and the files are successfully restored, the undo file should be removed.

See [restore_rmw.c](https://github.com/andy5995/rmw/blob/master/src/functions/restore_rmw.c)

**Comment by ajphukan** [comment]
If you are talking about this [function](https://github.com/andy5995/rmw/blob/master/src/functions/restore_rmw.c#L354)
We can add  remove function after undo file is closed  ...

**Comment by andy5995** [comment]
Yes.

If the return value of Restore() is 0, remove the undo file.

If you try this, send me the diff output before the PR. Use
git diff > 58.diff

That redirects the output to 58.diff. Copy the contents and make a paste on http://pastebin.com and send me the link.

**Comment by andy5995** [comment]
Make sure to use the directions for ["syncing"](https://github.com/andy5995/rmw/wiki/Contributing) the develop branch before you make any edits, else you will have a mess! :)

**Comment by ajphukan** [comment]
During my rmw 2nd PR , i somehow learned the syncing process dont worry ....

**Comment by ajphukan** [comment]
[loop](https://github.com/andy5995/rmw/blob/355578ea07a7f85120251ba9ddf7e1485c991720/src/functions/restore_rmw.c#L379)

fgets is called multiple time or just one , if one there will be no problem 
but if multiple times then there is a possibility that Restore will not return 0 .

**Comment by andy5995** [comment]
fgets will sometimes be called multiple times. It depends on how many files were rmw'ed the last time. You can try it:

```
mkdir temp
touch temp/{a..z}
rmw temp/*
cat $HOME/.config/testrmw/lastrmw (or $HOME/.config/rmw/lastrmw)
```

You will see 26 lines when you 'cat' lastrmw ;)

A counter can be used.

err_ctr += Restore (...

**Comment by ajphukan** [comment]
err_ctr nice idea ..

loop
{
err_ctr+=Restore(..);
}
if(err_ctr!=0)
{print sucess;
}
else
{print these files are no of files are not recovered
}
close(undo_file) // whether err is generated or not we have to remove the undo file .

if the pseudo code is okk i will create a PR for this ..

**Comment by andy5995** [comment]
Ankur, I'm on IRC right now if you care to touch base with me.

So the way to send me your suggested code is after you make the edits, run
git diff > patch-name.diff

Copy the contents of patch-name.diff to http://pastebin.com and then send me the link. Much easier to review code that way.

**Comment by ajphukan** [comment]
okk let me switch to linux  ...

**Comment by andy5995** [comment]
Well, that will work on Windows

**Comment by ajphukan** [comment]
[changes](http://pastebin.com/wWxe56GT)
