### ISSUE TITLE
Help message as default .

### ISSUE THREAD

**Issue by ajphukan** [andy5995/rmw#59]
Like other terminal commands we can show the help message if no flag and filename is given ..

**Comment by andy5995** [comment]
That's not a bad idea, but I don't see it as necessary. Not all terminal commands give the help output if not flags or filenames are given. Here's a comparison between 'rmw' and 'mv':

> andy@oceanus:~$ rmw
> missing filenames or command line options
> Try 'rmw -h' for more information
> 
> Purging files (purge_after = 45) ...
> 2 files purged
> andy@oceanus:~$ mv
> mv: missing file operand
> Try 'mv --help' for more information.

Thanks for the suggestion.

**Comment by ajphukan** [comment]
okk
