### ISSUE TITLE
is_time_to_purge: remove HOMEDIR as an argument 

### ISSUE THREAD

**Issue by andy5995** [andy5995/rmw#60]
In the function is_time_to_purge(), HOMEDIR should be removed as an argument and declared at the top of the function. @ajphukan Can you fix this?

https://github.com/andy5995/rmw/blob/develop/src/functions/purging_rmw.c#L136

**Comment by ajphukan** [comment]
remove the argument and declared it inside the function ?

**Comment by andy5995** [comment]
Thanks.

**Comment by ajphukan** [comment]
Welcome  ...
