### ISSUE TITLE
Optimize restore_select function

### ISSUE THREAD

**Issue by andy5995** [andy5995/rmw#64]
Optimize [restore_select function](https://github.com/andy5995/rmw/blob/master/src/functions/restore_rmw.c)

**Comment by ajphukan** [comment]
What type of optimization  you want ?

**Comment by andy5995** [comment]
I'm not sure yet. ;) I was looking at it last night and saw one area where it looked like a switch-case would be better.

I don't think I made any changes to that function since I originally wrote it 4 years ago and figured it needs to be looked at a bit more to see if can be written more efficiently. If you have any ideas and would like to work on it, just send me the output of 'git diff' through http://pastebin.com so I can review and comment before the PR. Thanks, Ankur.

**Comment by ajphukan** [comment]
okk i will try  ...

**Comment by ajphukan** [comment]
i think we can break the restore _select fun to smaller form 
restore_select ()
{loop(ch!=q)
  {
  display_list(..);
  ///let the user to select a number or quit ;
  if(ch!=q)
 restore(..)
 }
}

this can help new contributor understand ore quickly and optimization can be done separately ..

**Comment by andy5995** [comment]
I'm not sure I even want to touch it right now. It works! :) Thanks, but this can just sit for a while.

**Comment by ajphukan** [comment]
can i get your email id ....

**Comment by andy5995** [comment]
I need to review the code and potentially write a ticket with a narrower scope
