### ISSUE TITLE
May need some extra output when purging directories with many files

### ISSUE THREAD

**Issue by andy5995** [andy5995/rmw#67]
I had a bit of a delay just now when I ran 'rmw' and the auto-purge ran. After it was done, it said it removed 8 files. I reasoned that some of those must have been directories with a ton of files in them.

Not really sure if I'd call this a 'bug'. Plenty of system utilities will offer no output of what's happening when verbosity is turned off. cp and mv for example. But worth a ticket.

**Comment by andy5995** [comment]
There's some info on the [Testing](https://github.com/andy5995/rmw/wiki/Testing) wiki page that can help troubleshoot this.

Please remember to "star" this project (upper right corner) and [join the chat room](https://join.slack.com/t/removetowaste/shared_invite/enQtMjU3NTA0NTI2OTgzLTkzMzQxNDhjYzlkM2UxMTA2MzJjNWYyZjAyYzkyNWNmZjJmYWZmYjUyODk2NzNkNzBhMzFjOGZkMTg2MzAxMTM) if you like.

The [Contributing wiki page](https://github.com/andy5995/rmw/wiki/Contributing) contains important information about making pull requests.

**Comment by rlyshw** [comment]
even the system's `rm` gives no output without the -v flag, I think it'd be safe for rmw to be a "silent" utility, just like rm.

Here's a snippet of an `rm -rf -v` on a directory with several items inside.

```
rlyshw@claptrap:/tmp$ mkdir test
rlyshw@claptrap:/tmp$ cd test
rlyshw@claptrap:/tmp/test$ touch 1
rlyshw@claptrap:/tmp/test$ touch 2
rlyshw@claptrap:/tmp/test$ touch 3
rlyshw@claptrap:/tmp/test$ mkdir testtest
rlyshw@claptrap:/tmp/test$ cd testtest/
rlyshw@claptrap:/tmp/test/testtest$ touch 4
rlyshw@claptrap:/tmp/test/testtest$ touch 5
rlyshw@claptrap:/tmp/test/testtest$ touch 6
rlyshw@claptrap:/tmp/test/testtest$ cd /tmp
rlyshw@claptrap:/tmp$ rm -v -rf ./test
removed './test/2'
removed './test/1'
removed './test/3'
removed './test/testtest/6'
removed './test/testtest/5'
removed './test/testtest/4'
removed directory './test/testtest'
removed directory './test'
```

Recursive calls tell you exactly what was removed and where with a relative path.

**Comment by andy5995** [comment]
I respect that logic! Thanks for the input @rlyshw  Closing....
