### ISSUE TITLE
add message in escape_url() if buffer check fails

### ISSUE THREAD

**Issue by andy5995** [andy5995/rmw#69]
add message in escape_url() if buffer check fails

Right now, 1 is returned, but no output is displayed as to the reason for failure

https://github.com/andy5995/rmw/blob/511c666de9c7891012755d5e1661129911870189/src/functions/strings_rmw.c#L290

**Comment by suve** [comment]
I assume the message should go to `stderr`, not `stdout`. One question though: should it be governed by the `--verbose` flag?

**Comment by andy5995** [comment]
Hi @suve .

Yes, stderr.

Hmm.. no I don't think it should be governed by the verbose flag. If the buf_check fails at that point, there's most likely some problem in the program that needs to be fixed.
