### ISSUE TITLE
Building on OpenBSD

### ISSUE THREAD

**Issue by andy5995** [andy5995/rmw#70]
I installed OpenBSD 6.0 to a VDI in VirtualBox.

I got one fatal error when building - syscall.h couldn't be found. I checked /usr/include/sys and found it there. I made the edit and rmw finished building.

I saw syscall.h also exists in /usr/include/sys on my Linux system, so I'll be making the change to [rmw.h](https://github.com/andy5995/rmw/blob/master/src/rmw.h) permanent.

These are the warnings I got

```
./functions/messages_rmw.o
primary_funcs.o: In function `make_dir':
/home/andy/src/rmw-2016.09.19.01a/src/primary_funcs.c:55: warning:
warning: strcat() is almost always misused, please use strlcat()
/home/andy/src/rmw-2016.09.19.01a/src/primary_funcs.c:41: warning:
warning: strcpy() is almost always misused, please use strlcpy()
./functions/strings_rmw.o: In function `escape_url':
./functions/strings_rmw.c:269: warning: warning: sprintf() is often
misused, please use snprintf()
Making all in etc
```

I'm noob to OpenBSD, but wanted to see if I could get `rmw` working on the BSD systems. Seems to work okay.

**Comment by andy5995** [comment]
This could use some review and testing by BSD users.

**Comment by sexybiggetje** [comment]
Building and testing is confirmed to work correctly on FreeBSD-11.1-STABLE and OpenBSD-6.2 both with amd64 arch.

**Comment by andy5995** [comment]
Thank you, Martin!
