### ISSUE TITLE
man page should be installed during 'make install`

### ISSUE THREAD

**Issue by andy5995** [andy5995/rmw#81]
The man page should be installed during `make install`

**Comment by rlyshw** [comment]
I can work on this! I'm reading about automake and how all that stuff works. Looks like we just gotta copy the .man file into /usr/share/man/man1/rmw.1

Unsure about how to do multi-language support.

**Comment by andy5995** [comment]
cool!

>Unsure about how to do multi-language support.

Ok, no worries on that. I've opened up some more tickets and maybe we can get some recommendations about it.

For dev chat, we just switched to the Slack workspace today. Here's the [invite link](
https://join.slack.com/t/removetowaste/shared_invite/enQtMjU3NTA0NTI2OTgzLTkzMzQxNDhjYzlkM2UxMTA2MzJjNWYyZjAyYzkyNWNmZjJmYWZmYjUyODk2NzNkNzBhMzFjOGZkMTg2MzAxMTM)
