### ISSUE TITLE
German

### ISSUE THREAD

**Issue by kickbutts** [andy5995/rmw#82]
Hi would like to make a german translation. Interested?

**Comment by andy5995** [comment]
Yes, that would be great! I have no idea how to add translations, so any help with that would be appreciated! Vielen Dank!

**Comment by kickbutts** [comment]
You are welcome. I will amke a new file rmw-de.man and add my translation.

**Comment by andy5995** [comment]
For dev chat, we just switched to the Slack workspace today. Here's the [invite link](
https://join.slack.com/t/removetowaste/shared_invite/enQtMjU3NTA0NTI2OTgzLTkzMzQxNDhjYzlkM2UxMTA2MzJjNWYyZjAyYzkyNWNmZjJmYWZmYjUyODk2NzNkNzBhMzFjOGZkMTg2MzAxMTM)

**Comment by kickbutts** [comment]
Done. Have a look if this fits your needs.

**Comment by andy5995** [comment]
Looks good! I am not fluent in German but if there are any problems, they will be found by other people. :) Thanks.

If you would like to re-submit your patch as a PR (so you can receive credit for Hacktoberfest) please let me know.

**Comment by kickbutts** [comment]
Submitting my Patch as PR for The Hacktoberfest would be nice.
Thanks.

**Comment by andy5995** [comment]
@kickbutts  I will need to reset the master to a previous commit before you submit the PR. Do you need any assistance getting your PR prepared?

**Comment by kickbutts** [comment]
yes. Actually i dont know what to do.

**Comment by andy5995** [comment]
* make a copy of `rmw-de.man` and put it outside of the rmw github directory.
* delete the rmw github directory

Then follow the instructions here: https://github.com/andy5995/rmw/wiki/Contributing#pull-requests

At step 4 on that page, copy `rmw-de.man` to the rmw/man directory.

Then proceed to step 5.

Let me know if you get stuck anywhere or if my instructions are not clear.

**Comment by kickbutts** [comment]
Done. Hope its working.

**Comment by andy5995** [comment]
Yes, perfectly.

(fixed via PR andy5995/rmw#86)
